### ISSUE TITLE
elevation map doesnt appear in the topics (in Rviz)

### ISSUE THREAD

**Issue by Artinmi** [Muhammad540/elevation_mapping#2]
I have used this package in ROS1 and i was looking for its alternative in ROS2 humble finally we have found your repo but after all of the modifications in the params and yaml files( we have provide its poincloud and the Pose topics) but after launching the main node : " ros2 launch elevation_mapping elevationMapping_launch.py "  the Rviz will get open but nothing gets published in title of elevation_map_ raw or anything. its like nothing is happenning and nothing gets published but yet we dont get any error to debug it. Can you provide your own parameters mofifications? IS THIS PACKAGE EVEN WORKING? OR ITS FAKE?

**Comment by Muhammad540** [comment]
Hey @Artinmi , I'm not entirely sure what might be causing the issue you're facing with such limited information that you provided. We used this on our system a while back, and it seemed to be working fine. Just to clarify, this is a very minimal port of elevation mapping from ROS1 just to get up and running. 

That said, I should mention that we’ve moved away from using Anybotics’ elevation mapping or traversability estimation. Taking inspiration we’ve developed a lightweight version tailored to our needs, so I’m no longer actively working with the original package. Unfortunately, due to time constraints, I’m unable to assist with your questions. Apologies for the inconvenience!

**Comment by Artinmi** [comment]
Thanks for your cincere feedback. We are developing a quadruped robot for our lab. And we really need a little help from you. Are you sure that you cant allocate  15 minute to have video call with us ? Let me know if you were able
